/**
 * JSON-UI Maker - MCADDON Preview Exporter
 *
 * Exports the current editor project as a ready-to-import .mcaddon:
 *   - Resource Pack: generated JSON UI + server_form bridge + textures
 *   - Behavior Pack: /scriptevent rag:<name> preview command
 *
 * Built-in texture sets bundled automatically:
 *   eternal, other, pink, red, turquoise
 *
 * No external ZIP library is required. The exporter writes an uncompressed ZIP
 * directly in the browser, which Minecraft accepts as .mcaddon.
 */
(() => {
    "use strict";

    if (window.__JSON_UI_MAKER_MCADDON_EXPORTER__) return;
    window.__JSON_UI_MAKER_MCADDON_EXPORTER__ = true;

    const BUILTIN_TEXTURE_SETS = [
        "eternal_ore-ui_style",
        "other_ore-ui_style",
        "pink_ore-ui_style",
        "red_ore-ui_style",
        "turquoise_ore-ui_style",
    ];

    const VERSION = [1, 0, 0];
    const textEncoder = new TextEncoder();

    let indexModule = null;
    let configModule = null;
    let jsonTypesModule = null;
    let converterModule = null;

    function uuid() {
        if (crypto.randomUUID) return crypto.randomUUID();

        const b = new Uint8Array(16);
        crypto.getRandomValues(b);
        b[6] = (b[6] & 0x0f) | 0x40;
        b[8] = (b[8] & 0x3f) | 0x80;

        return [...b]
            .map((v, i) =>
                ([4, 6, 8, 10].includes(i) ? "-" : "") +
                v.toString(16).padStart(2, "0")
            )
            .join("");
    }

    function sanitizeIdentifier(value) {
        let s = String(value ?? "")
            .normalize("NFD")
            .replace(/[\u0300-\u036f]/g, "")
            .toLowerCase()
            .replace(/[^a-z0-9_.-]+/g, "_")
            .replace(/^[_\-.]+|[_\-.]+$/g, "");

        if (!s) s = "preview";
        return s.slice(0, 48);
    }

    function sanitizeFileName(value) {
        let s = String(value ?? "")
            .normalize("NFD")
            .replace(/[\u0300-\u036f]/g, "")
            .replace(/[<>:"/\\|?*\u0000-\u001f]+/g, "_")
            .replace(/\s+/g, "_")
            .replace(/^_+|_+$/g, "");

        if (!s) s = "RAG_UI_PREVIEW";
        return s.slice(0, 80);
    }

    function stripGeneratedComment(jsonText) {
        return String(jsonText).replace(
            /\s*\/\*\s*Generated by JSON-UI Maker[\s\S]*?\*\/\s*$/i,
            ""
        );
    }

    function makeGameUiJson(raw) {
        const parsed = JSON.parse(stripGeneratedComment(raw));
        // "config" is editor import metadata, not a Bedrock UI control.
        delete parsed.config;
        return JSON.stringify(parsed, null, 4);
    }

    async function loadEditorModules() {
        if (!indexModule) indexModule = await import("./dist/index.js");
        if (!configModule) configModule = await import("./dist/CONFIG.js");
        if (!jsonTypesModule) {
            jsonTypesModule = await import("./dist/converterTypes/jsonUITypes.js");
        }
        if (!converterModule) converterModule = await import("./dist/converter.js");

        return {
            index: indexModule,
            config: configModule.config,
            JSON_TYPES_GENERATOR: jsonTypesModule.JSON_TYPES_GENERATOR,
            Converter: converterModule.Converter,
        };
    }

    function getButtonPreviewData(mainWindow) {
        const buttons = [...mainWindow.querySelectorAll(".draggable-button[data-collection-index]")];

        const byIndex = new Map();

        for (const button of buttons) {
            const index = Number(button.dataset.collectionIndex);
            if (!Number.isInteger(index) || index < 0) continue;

            const nestedLabel = button.querySelector("textarea.draggable-label");
            const nestedCanvas = [...button.querySelectorAll(".draggable-canvas[data-image-path]")]
                .find((el) => el.dataset.shouldParse === "false") ||
                button.querySelector(".draggable-canvas[data-image-path]");

            const text =
                nestedLabel?.value?.trim() ||
                button.dataset.displayText?.trim() ||
                `BOTAO ${index + 1}`;

            const imagePath =
                nestedCanvas?.dataset.imagePath?.trim() ||
                button.dataset.displayImagePath?.trim() ||
                "";

            byIndex.set(index, {
                text,
                imagePath,
            });
        }

        if (byIndex.size === 0) {
            return [{ text: "PREVIEW", imagePath: "" }];
        }

        const maxIndex = Math.max(...byIndex.keys());
        const result = [];

        for (let i = 0; i <= maxIndex; i++) {
            result.push(
                byIndex.get(i) || {
                    text: `PREVIEW ${i + 1}`,
                    imagePath: "",
                }
            );
        }

        return result;
    }

    function generatePreviewScript(eventName, titleFlag, buttons) {
        const eventId = `rag:${eventName}`;

        const serializedButtons = JSON.stringify(
            buttons.map((button) => ({
                text: button.text,
                imagePath: button.imagePath
                    ? `textures/${button.imagePath.replace(/^textures\//, "")}`
                    : "",
            })),
            null,
            4
        );

        return `import { system, Player } from "@minecraft/server";
import { ActionFormData } from "@minecraft/server-ui";

const EVENT_ID = ${JSON.stringify(eventId)};
const TITLE_FLAG = ${JSON.stringify(titleFlag)};
const BUTTONS = ${serializedButtons};

async function showPreview(player) {
    const form = new ActionFormData()
        .title(TITLE_FLAG);

    for (const button of BUTTONS) {
        if (button.imagePath) {
            form.button(button.text, button.imagePath);
        } else {
            form.button(button.text);
        }
    }

    try {
        const response = await form.show(player);

        if (!response.canceled && response.selection !== undefined) {
            player.sendMessage(\`§a[RAG Preview] §fBotao selecionado: §e\${response.selection}\`);
        }
    } catch (error) {
        player.sendMessage(\`§c[RAG Preview] Falha ao abrir o form: \${error}\`);
    }
}

system.afterEvents.scriptEventReceive.subscribe((event) => {
    if (event.id !== EVENT_ID) return;

    const player = event.sourceEntity;

    if (!(player instanceof Player)) {
        return;
    }

    // Defer one tick so the form is opened outside the event callback itself.
    system.run(() => {
        showPreview(player);
    });
});
`;
    }

    function createResourceManifest(packName, rpHeaderUuid, rpModuleUuid) {
        return JSON.stringify(
            {
                format_version: 2,
                header: {
                    name: `${packName} | RP`,
                    description: "RAG JSON-UI preview resource pack",
                    uuid: rpHeaderUuid,
                    version: VERSION,
                    min_engine_version: [1, 21, 0],
                },
                modules: [
                    {
                        type: "resources",
                        uuid: rpModuleUuid,
                        version: VERSION,
                    },
                ],
                metadata: {
                    authors: ["RAG JSON-UI Maker"],
                    generated_with: {
                        rag_json_ui_maker: ["1.0.0"],
                    },
                },
            },
            null,
            4
        );
    }

    function createBehaviorManifest(
        packName,
        bpHeaderUuid,
        bpDataUuid,
        bpScriptUuid,
        rpHeaderUuid
    ) {
        return JSON.stringify(
            {
                format_version: 2,
                header: {
                    name: `${packName} | BP PREVIEW`,
                    description: "Temporary preview command for exported JSON UI",
                    uuid: bpHeaderUuid,
                    version: VERSION,
                    min_engine_version: [1, 21, 0],
                },
                modules: [
                    {
                        type: "data",
                        uuid: bpDataUuid,
                        version: VERSION,
                    },
                    {
                        type: "script",
                        language: "javascript",
                        entry: "scripts/main.js",
                        uuid: bpScriptUuid,
                        version: VERSION,
                    },
                ],
                dependencies: [
                    {
                        module_name: "@minecraft/server",
                        version: "2.8.0",
                    },
                    {
                        module_name: "@minecraft/server-ui",
                        version: "2.1.0",
                    },
                    {
                        uuid: rpHeaderUuid,
                        version: VERSION,
                    },
                ],
                metadata: {
                    authors: ["RAG JSON-UI Maker"],
                    generated_with: {
                        rag_json_ui_maker: ["1.0.0"],
                    },
                },
            },
            null,
            4
        );
    }

    function createPackIcon(label) {
        const canvas = document.createElement("canvas");
        canvas.width = 256;
        canvas.height = 256;

        const ctx = canvas.getContext("2d");

        const gradient = ctx.createLinearGradient(0, 0, 256, 256);
        gradient.addColorStop(0, "#161616");
        gradient.addColorStop(0.5, "#5b167f");
        gradient.addColorStop(1, "#d20077");

        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, 256, 256);

        ctx.fillStyle = "rgba(255,255,255,.11)";
        for (let y = 0; y < 256; y += 32) {
            for (let x = (y / 32) % 2 ? 16 : 0; x < 256; x += 32) {
                ctx.fillRect(x, y, 16, 16);
            }
        }

        ctx.strokeStyle = "rgba(255,255,255,.8)";
        ctx.lineWidth = 8;
        ctx.strokeRect(12, 12, 232, 232);

        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillStyle = "#fff";
        ctx.font = "bold 58px sans-serif";
        ctx.fillText("RAG", 128, 104);

        ctx.font = "bold 25px sans-serif";
        ctx.fillText("UI PREVIEW", 128, 158);

        ctx.font = "16px sans-serif";
        const shortLabel = String(label).slice(0, 22);
        ctx.fillText(shortLabel, 128, 198);

        return new Promise((resolve, reject) => {
            canvas.toBlob((blob) => {
                if (blob) resolve(blob);
                else reject(new Error("Nao foi possivel gerar pack_icon.png"));
            }, "image/png");
        });
    }

    async function imageDataToPngBlob(imageData) {
        const canvas = document.createElement("canvas");
        canvas.width = imageData.width;
        canvas.height = imageData.height;
        canvas.getContext("2d").putImageData(imageData, 0, 0);

        return new Promise((resolve, reject) => {
            canvas.toBlob((blob) => {
                if (blob) resolve(blob);
                else reject(new Error("Falha ao converter textura para PNG"));
            }, "image/png");
        });
    }

    function normalizedTexturePath(key, extension) {
        let path = String(key)
            .replace(/^textures\//, "")
            .replace(/\.(png|jpg|jpeg|webp|tga|json)$/i, "")
            .replace(/^\/+/, "");

        return `textures/${path}.${extension}`;
    }

    async function addLoadedEditorTextures(files, rpRoot, images) {
        let count = 0;

        for (const [key, state] of images.entries()) {
            if (!state) continue;

            if (state.png) {
                const blob = await imageDataToPngBlob(state.png);
                files.set(
                    `${rpRoot}/${normalizedTexturePath(key, "png")}`,
                    blob
                );
                count++;
            }

            if (state.json) {
                files.set(
                    `${rpRoot}/${normalizedTexturePath(key, "json")}`,
                    JSON.stringify(state.json, null, 4)
                );
            }
        }

        return count;
    }

    async function fetchBlobChecked(url) {
        const response = await fetch(url, { cache: "no-store" });
        if (!response.ok) {
            throw new Error(`${response.status} ${response.statusText}: ${url}`);
        }
        return response.blob();
    }

    async function fetchJsonChecked(url) {
        const response = await fetch(url, { cache: "no-store" });
        if (!response.ok) {
            throw new Error(`${response.status} ${response.statusText}: ${url}`);
        }
        return response.json();
    }

    async function addBuiltinTextureSets(files, rpRoot, onProgress) {
        let count = 0;
        const warnings = [];

        for (let setIndex = 0; setIndex < BUILTIN_TEXTURE_SETS.length; setIndex++) {
            const setName = BUILTIN_TEXTURE_SETS[setIndex];

            onProgress?.(
                `Incluindo texturas ${setName.replace("_ore-ui_style", "")}...`
            );

            try {
                const mapping = await fetchJsonChecked(
                    `presets/textures/${setName}/mapping.json`
                );

                const entries = Array.isArray(mapping?.data) ? mapping.data : [];

                for (const entry of entries) {
                    const image = entry?.image;
                    if (!image) continue;

                    try {
                        const png = await fetchBlobChecked(
                            `presets/textures/${setName}/${image}.png`
                        );

                        files.set(
                            `${rpRoot}/textures/presets/textures/${setName}/${image}.png`,
                            png
                        );
                        count++;

                        if (entry.nineslice) {
                            const json = await fetchJsonChecked(
                                `presets/textures/${setName}/${image}.json`
                            );

                            files.set(
                                `${rpRoot}/textures/presets/textures/${setName}/${image}.json`,
                                JSON.stringify(json, null, 4)
                            );
                        }
                    } catch (error) {
                        warnings.push(String(error));
                    }
                }
            } catch (error) {
                warnings.push(String(error));
            }
        }

        return { count, warnings };
    }

    function makeUiDefs(namespace) {
        return JSON.stringify(
            {
                ui_defs: [
                    "ui/server_form.json",
                    `ui/${namespace}.json`,
                ],
            },
            null,
            4
        );
    }

    function makePreviewReadme(command, namespace, titleFlag, textureCount) {
        return `RAG JSON-UI PREVIEW

COMANDO DE TESTE
${command}

Este Behavior Pack existe apenas para previa.
A UI reutilizavel esta no Resource Pack.

ARQUIVOS PRINCIPAIS
- ui/${namespace}.json
- ui/server_form.json
- ui/_ui_defs.json
- textures/...

TITLE FLAG
${titleFlag}

TEXTURAS EMPACOTADAS
${textureCount}

O preview usa ActionFormData apenas para alimentar a collection "form_buttons".
`;
    }

    // ---------- Tiny ZIP writer (STORE / no compression) ----------

    const CRC_TABLE = (() => {
        const table = new Uint32Array(256);

        for (let n = 0; n < 256; n++) {
            let c = n;

            for (let k = 0; k < 8; k++) {
                c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
            }

            table[n] = c >>> 0;
        }

        return table;
    })();

    function crc32(bytes) {
        let crc = 0xffffffff;

        for (let i = 0; i < bytes.length; i++) {
            crc = CRC_TABLE[(crc ^ bytes[i]) & 0xff] ^ (crc >>> 8);
        }

        return (crc ^ 0xffffffff) >>> 0;
    }

    function dosTimeDate(date = new Date()) {
        const year = Math.max(1980, date.getFullYear());

        const time =
            (date.getHours() << 11) |
            (date.getMinutes() << 5) |
            Math.floor(date.getSeconds() / 2);

        const dosDate =
            ((year - 1980) << 9) |
            ((date.getMonth() + 1) << 5) |
            date.getDate();

        return { time, date: dosDate };
    }

    function u16(view, offset, value) {
        view.setUint16(offset, value, true);
    }

    function u32(view, offset, value) {
        view.setUint32(offset, value >>> 0, true);
    }

    async function toBytes(value) {
        if (value instanceof Uint8Array) return value;
        if (value instanceof ArrayBuffer) return new Uint8Array(value);
        if (value instanceof Blob) return new Uint8Array(await value.arrayBuffer());
        return textEncoder.encode(String(value));
    }

    function concatUint8(parts) {
        const total = parts.reduce((sum, p) => sum + p.length, 0);
        const output = new Uint8Array(total);
        let offset = 0;

        for (const part of parts) {
            output.set(part, offset);
            offset += part.length;
        }

        return output;
    }

    async function makeZip(fileMap) {
        const localParts = [];
        const centralParts = [];
        let localOffset = 0;
        let entries = 0;

        const { time, date } = dosTimeDate();

        for (const [rawName, value] of fileMap.entries()) {
            const name = rawName.replace(/\\/g, "/").replace(/^\/+/, "");
            const nameBytes = textEncoder.encode(name);
            const data = await toBytes(value);
            const crc = crc32(data);

            const localHeader = new Uint8Array(30);
            const lv = new DataView(localHeader.buffer);

            u32(lv, 0, 0x04034b50);
            u16(lv, 4, 20);
            u16(lv, 6, 0x0800); // UTF-8
            u16(lv, 8, 0); // STORE
            u16(lv, 10, time);
            u16(lv, 12, date);
            u32(lv, 14, crc);
            u32(lv, 18, data.length);
            u32(lv, 22, data.length);
            u16(lv, 26, nameBytes.length);
            u16(lv, 28, 0);

            localParts.push(localHeader, nameBytes, data);

            const central = new Uint8Array(46);
            const cv = new DataView(central.buffer);

            u32(cv, 0, 0x02014b50);
            u16(cv, 4, 20);
            u16(cv, 6, 20);
            u16(cv, 8, 0x0800);
            u16(cv, 10, 0);
            u16(cv, 12, time);
            u16(cv, 14, date);
            u32(cv, 16, crc);
            u32(cv, 20, data.length);
            u32(cv, 24, data.length);
            u16(cv, 28, nameBytes.length);
            u16(cv, 30, 0);
            u16(cv, 32, 0);
            u16(cv, 34, 0);
            u16(cv, 36, 0);
            u32(cv, 38, 0);
            u32(cv, 42, localOffset);

            centralParts.push(central, nameBytes);

            localOffset += localHeader.length + nameBytes.length + data.length;
            entries++;
        }

        const centralBytes = concatUint8(centralParts);
        const end = new Uint8Array(22);
        const ev = new DataView(end.buffer);

        u32(ev, 0, 0x06054b50);
        u16(ev, 4, 0);
        u16(ev, 6, 0);
        u16(ev, 8, entries);
        u16(ev, 10, entries);
        u32(ev, 12, centralBytes.length);
        u32(ev, 16, localOffset);
        u16(ev, 20, 0);

        return new Blob(
            [...localParts, centralBytes, end],
            { type: "application/zip" }
        );
    }

    function downloadBlob(blob, filename) {
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");

        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        a.remove();

        setTimeout(() => URL.revokeObjectURL(url), 5000);
    }

    function setStatus(modal, text, kind = "normal") {
        const status = modal.querySelector(".rag-export-status");
        if (!status) return;

        status.textContent = text;
        status.dataset.kind = kind;
    }

    async function exportMcaddon(modal, rawName) {
        const { index, config, JSON_TYPES_GENERATOR, Converter } =
            await loadEditorModules();

        const eventName = sanitizeIdentifier(rawName);
        const packDisplayName = `RAG UI PREVIEW - ${eventName}`;
        const fileBase = sanitizeFileName(`RAG_UI_${eventName}`);

        const mainWindow = document.getElementById("main_window");
        if (!mainWindow) {
            throw new Error("main_window nao encontrado.");
        }

        if (!config.rootElement) {
            throw new Error("Crie/carregue um form antes de exportar.");
        }

        setStatus(modal, "Gerando JSON UI...");

        const rawUi = Converter.convertToJsonUi(index.panelContainer, 0);
        const gameUi = makeGameUiJson(rawUi);

        const namespace = config.nameSpace;
        const titleFlag = config.title_flag;

        const serverFormGenerator = JSON_TYPES_GENERATOR.get("server_form");
        if (!serverFormGenerator) {
            throw new Error("Gerador server_form nao encontrado.");
        }

        const serverForm = serverFormGenerator(namespace);
        const previewButtons = getButtonPreviewData(mainWindow);

        const rpHeaderUuid = uuid();
        const rpModuleUuid = uuid();
        const bpHeaderUuid = uuid();
        const bpDataUuid = uuid();
        const bpScriptUuid = uuid();

        const rpRoot = `${fileBase}_RP`;
        const bpRoot = `${fileBase}_BP`;

        const files = new Map();

        files.set(
            `${rpRoot}/manifest.json`,
            createResourceManifest(packDisplayName, rpHeaderUuid, rpModuleUuid)
        );

        files.set(
            `${bpRoot}/manifest.json`,
            createBehaviorManifest(
                packDisplayName,
                bpHeaderUuid,
                bpDataUuid,
                bpScriptUuid,
                rpHeaderUuid
            )
        );

        const packIcon = await createPackIcon(eventName);
        files.set(`${rpRoot}/pack_icon.png`, packIcon);
        files.set(`${bpRoot}/pack_icon.png`, packIcon);

        files.set(`${rpRoot}/ui/${namespace}.json`, gameUi);
        files.set(`${rpRoot}/ui/server_form.json`, serverForm);
        files.set(`${rpRoot}/ui/_ui_defs.json`, makeUiDefs(namespace));

        files.set(
            `${bpRoot}/scripts/main.js`,
            generatePreviewScript(eventName, titleFlag, previewButtons)
        );

        setStatus(modal, "Incluindo texturas carregadas no editor...");

        const loadedTextureCount = await addLoadedEditorTextures(
            files,
            rpRoot,
            index.images
        );

        const builtin = await addBuiltinTextureSets(
            files,
            rpRoot,
            (message) => setStatus(modal, message)
        );

        const totalTextures = loadedTextureCount + builtin.count;
        const command = `/scriptevent rag:${eventName}`;

        files.set(
            `${fileBase}_LEIA-ME.txt`,
            makePreviewReadme(command, namespace, titleFlag, totalTextures)
        );

        files.set(
            `${bpRoot}/PREVIEW_COMMAND.txt`,
            `${command}\n`
        );

        setStatus(
            modal,
            `Empacotando ${files.size} arquivos (${totalTextures} texturas)...`
        );

        const zip = await makeZip(files);

        downloadBlob(zip, `${fileBase}.mcaddon`);

        if (builtin.warnings.length) {
            console.warn(
                "[RAG MCADDON Export] Algumas texturas de preset nao puderam ser baixadas:",
                builtin.warnings
            );
        }

        setStatus(
            modal,
            `Pronto! Teste no Minecraft com: ${command}`,
            "success"
        );

        const commandBox = modal.querySelector(".rag-export-command");
        if (commandBox) commandBox.textContent = command;
    }

    function closeModal(modal) {
        modal.remove();
    }

    function openExportModal() {
        const old = document.getElementById("ragMcaddonExportModal");
        old?.remove();

        const modal = document.createElement("div");
        modal.id = "ragMcaddonExportModal";
        modal.className = "rag-export-overlay";

        const card = document.createElement("div");
        card.className = "rag-export-card";

        const title = document.createElement("h2");
        title.textContent = "EXPORTAR PREVIEW .MCADDON";

        const body = document.createElement("p");
        body.textContent =
            "Gera RP + BP de teste. As texturas red, eternal, pink, turquoise, other e as texturas carregadas no editor entram automaticamente.";

        const label = document.createElement("label");
        label.textContent = "Nome do form / comando:";

        const input = document.createElement("input");
        input.type = "text";
        input.value = "preview";
        input.placeholder = "ex: loja_vips";
        input.className = "rag-export-input";
        input.autocapitalize = "off";
        input.autocomplete = "off";
        input.spellcheck = false;

        const commandTitle = document.createElement("div");
        commandTitle.className = "rag-export-command-title";
        commandTitle.textContent = "Comando no Bedrock:";

        const command = document.createElement("code");
        command.className = "rag-export-command";
        command.textContent = "/scriptevent rag:preview";

        const status = document.createElement("div");
        status.className = "rag-export-status";
        status.textContent = "Aguardando exportacao.";

        const actions = document.createElement("div");
        actions.className = "rag-export-actions";

        const cancel = document.createElement("button");
        cancel.type = "button";
        cancel.textContent = "CANCELAR";

        const exportButton = document.createElement("button");
        exportButton.type = "button";
        exportButton.textContent = "EXPORTAR .MCADDON";
        exportButton.className = "rag-export-primary";

        input.addEventListener("input", () => {
            command.textContent =
                `/scriptevent rag:${sanitizeIdentifier(input.value)}`;
        });

        cancel.addEventListener("click", () => closeModal(modal));

        exportButton.addEventListener("click", async () => {
            exportButton.disabled = true;
            cancel.disabled = true;
            input.disabled = true;

            try {
                await exportMcaddon(modal, input.value);
                cancel.disabled = false;
                cancel.textContent = "FECHAR";
            } catch (error) {
                console.error("[RAG MCADDON Export]", error);
                setStatus(
                    modal,
                    `Erro: ${error?.message || error}`,
                    "error"
                );
                cancel.disabled = false;
            } finally {
                exportButton.disabled = false;
                input.disabled = false;
            }
        });

        actions.append(cancel, exportButton);
        card.append(
            title,
            body,
            label,
            input,
            commandTitle,
            command,
            status,
            actions
        );
        modal.appendChild(card);
        document.body.appendChild(modal);

        input.focus();
        input.select();
    }

    function installStyle() {
        if (document.getElementById("ragMcaddonExportStyle")) return;

        const style = document.createElement("style");
        style.id = "ragMcaddonExportStyle";
        style.textContent = `
.rag-export-overlay {
    position: fixed;
    inset: 0;
    z-index: 200000;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 18px;
    background: rgba(0,0,0,.72);
    backdrop-filter: blur(4px);
}

.rag-export-card {
    width: min(520px, calc(100vw - 36px));
    max-height: calc(100vh - 36px);
    overflow: auto;
    box-sizing: border-box;
    padding: 20px;
    border: 2px solid #9900ff;
    border-radius: 14px;
    background: #2d2d2f;
    color: white;
    box-shadow: 0 18px 70px rgba(0,0,0,.55);
}

.rag-export-card h2 {
    margin: 0 0 10px;
    font-size: 21px;
}

.rag-export-card p {
    margin: 0 0 18px;
    color: #c8c8c8;
    line-height: 1.45;
    font-size: 13px;
}

.rag-export-card label,
.rag-export-command-title {
    display: block;
    margin: 12px 0 6px;
    color: #e4e4e4;
    font-weight: 700;
    font-size: 13px;
}

.rag-export-input {
    box-sizing: border-box;
    width: 100%;
    min-height: 46px;
    padding: 10px 12px;
    border: 1px solid #666;
    border-radius: 8px;
    outline: none;
    background: #1c1c1e;
    color: white;
    font-size: 16px;
}

.rag-export-input:focus {
    border-color: #b22cff;
}

.rag-export-command {
    display: block;
    overflow-x: auto;
    padding: 12px;
    border-radius: 8px;
    background: #141414;
    color: #d796ff;
    white-space: nowrap;
    user-select: all;
}

.rag-export-status {
    margin-top: 14px;
    min-height: 20px;
    padding: 10px 12px;
    border-radius: 8px;
    background: rgba(255,255,255,.06);
    color: #ccc;
    font-size: 12px;
    line-height: 1.35;
}

.rag-export-status[data-kind="success"] {
    color: #94f6ae;
    background: rgba(30,180,70,.13);
}

.rag-export-status[data-kind="error"] {
    color: #ff9d9d;
    background: rgba(220,30,30,.14);
}

.rag-export-actions {
    display: flex;
    gap: 10px;
    margin-top: 16px;
}

.rag-export-actions button {
    flex: 1;
    min-height: 46px;
    padding: 10px;
    border: 1px solid #666;
    border-radius: 8px;
    background: #3b3b40;
    color: white;
    font-weight: 800;
    cursor: pointer;
}

.rag-export-actions .rag-export-primary {
    border-color: #a827ef;
    background: linear-gradient(135deg, #7412ad, #c00075);
}

.rag-export-actions button:disabled {
    opacity: .55;
    cursor: wait;
}

.rag-mcaddon-export-button {
    min-height: 42px;
    font-weight: 800;
    border: 1px solid #9828db !important;
    background: linear-gradient(135deg, #4a1767, #84134f) !important;
}

@media (pointer: coarse) {
    .rag-export-card {
        width: min(560px, calc(100vw - 20px));
        padding: 17px;
    }

    .rag-export-actions {
        flex-direction: column;
    }

    .rag-export-actions button {
        min-height: 52px;
        font-size: 14px;
    }
}
`;
        document.head.appendChild(style);
    }

    function installButton() {
        if (document.querySelector(".rag-mcaddon-export-button")) return;

        const util = document.querySelector(".utilElements");
        if (!util) {
            setTimeout(installButton, 100);
            return;
        }

        const divider = document.createElement("div");
        divider.className = "breaker rag-export-breaker";

        const button = document.createElement("button");
        button.type = "button";
        button.className = "utilElement rag-mcaddon-export-button";
        button.textContent = "Exportar Preview .MCADDON";
        button.addEventListener("click", openExportModal);

        util.append(divider, button);
    }

    function init() {
        installStyle();
        installButton();
    }

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", init, { once: true });
    } else {
        init();
    }
})();
